version: "1.0"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - frontend
    command: ["nginx", "-g", "daemon off;"]

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: ["npm", "run", "dev"]
    volumes:
      - ./:/usr/workspace/